/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-everywhere": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Everywhere
         * @description Revoke every session. The control for a lost device (T7).
         */
        post: operations["logout_everywhere_api_v1_auth_logout_everywhere_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diary-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diary */
        get: operations["list_diary_api_v1_diary_events_get"];
        put?: never;
        /** Create Diary */
        post: operations["create_diary_api_v1_diary_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Doses */
        get: operations["list_doses_api_v1_doses_get"];
        put?: never;
        /** Create Dose */
        post: operations["create_dose_api_v1_doses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doses/plan-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan Comparison
         * @description Compare a day's doses with the plan in force that day.
         *
         *     Missing slots are derived from the absence of a dose. No zero-dose row exists or is
         *     created (SAFE-10).
         */
        get: operations["plan_comparison_api_v1_doses_plan_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doses/{dose_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Dose
         * @description Correct a dose. The original stays queryable with its original values (SAFE-08).
         */
        post: operations["correct_dose_api_v1_doses__dose_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emergency-injections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Injections */
        get: operations["list_injections_api_v1_emergency_injections_get"];
        put?: never;
        /**
         * Log Injection
         * @description Log an emergency injection.
         *
         *     Deliberately depends on nothing but the database: no AI call, no integration, no
         *     background job (SAFE-23). Everything beyond medication, amount, unit, and time is
         *     optional, because a partial record now beats a complete record later.
         */
        post: operations["log_injection_api_v1_emergency_injections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/garmin/imports/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Import Route
         * @description Reparse and confirm an unchanged preview as immutable recorded facts.
         */
        post: operations["confirm_import_route_api_v1_integrations_garmin_imports_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/garmin/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Import
         * @description Parse locally and return candidates; this endpoint creates no facts.
         */
        post: operations["preview_import_api_v1_integrations_garmin_imports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Lab Document
         * @description Quarantine a bounded PDF for the no-network structural validation worker.
         */
        post: operations["upload_lab_document_api_v1_labs_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Document */
        get: operations["get_lab_document_api_v1_labs_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Lab Document */
        delete: operations["delete_lab_document_api_v1_labs_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Lab Document */
        get: operations["download_lab_document_api_v1_labs_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/documents/{document_id}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Document Extraction */
        get: operations["get_lab_document_extraction_api_v1_labs_documents__document_id__extraction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/imports/csv/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Csv Route */
        post: operations["confirm_csv_route_api_v1_labs_imports_csv_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/imports/csv/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Csv */
        post: operations["preview_csv_api_v1_labs_imports_csv_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/labs/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Lab */
        post: operations["create_manual_lab_api_v1_labs_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/life-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Life Events */
        get: operations["list_life_events_api_v1_life_events_get"];
        put?: never;
        /** Create Life Event */
        post: operations["create_life_event_api_v1_life_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Medications */
        get: operations["list_medications_api_v1_medications_get"];
        put?: never;
        /** Create Medication */
        post: operations["create_medication_api_v1_medications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regimens */
        get: operations["list_regimens_api_v1_regimens_get"];
        put?: never;
        /**
         * Create Regimen
         * @description Create a *draft*. Drafts are never in force; approval is a separate act.
         */
        post: operations["create_regimen_api_v1_regimens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regimens/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Regimen
         * @description The approved version in force now, or null.
         *
         *     Null is a real answer and the UI must say "no approved plan" rather than falling
         *     back to the newest draft.
         */
        get: operations["active_regimen_api_v1_regimens_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regimens/{version_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Regimen
         * @description Record a physician's approval.
         *
         *     This endpoint is reachable only by an authenticated human with a CSRF token. There
         *     is no AI-callable path to it, and the AI database role could not write the row
         *     anyway (SAFE-16).
         */
        post: operations["approve_regimen_api_v1_regimens__version_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regimens/{version_id}/diff/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Regimens */
        get: operations["diff_regimens_api_v1_regimens__version_id__diff__other_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regimens/{version_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Regimen */
        post: operations["retire_regimen_api_v1_regimens__version_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stress-episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Episodes */
        get: operations["list_episodes_api_v1_stress_episodes_get"];
        put?: never;
        /** Create Episode */
        post: operations["create_episode_api_v1_stress_episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stress-episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Episode
         * @description Update an open episode.
         *
         *     An episode is a container the owner curates while it is happening, so it is
         *     genuinely mutable -- unlike the recorded facts inside it, which are corrected by
         *     supersession.
         */
        patch: operations["update_episode_api_v1_stress_episodes__episode_id__patch"];
        trace?: never;
    };
    "/api/v1/symptoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Symptoms */
        get: operations["list_symptoms_api_v1_symptoms_get"];
        put?: never;
        /** Create Symptom */
        post: operations["create_symptom_api_v1_symptoms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symptoms/{event_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Symptom */
        post: operations["correct_symptom_api_v1_symptoms__event_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description The unified timeline.
         *
         *     Every item carries its own category, source, timezone, and correction state, so a
         *     reader can tell a confirmed manual entry from a provider import at a glance
         *     (SAFE-02, plan section 10).
         */
        get: operations["timeline_api_v1_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Emergency Page */
        get: operations["emergency_page_emergency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergency/injection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Injection Form
         * @description Form-post injection logging, so it works without JavaScript.
         *
         *     Uses the moment of submission as the event time -- in an emergency, asking the
         *     owner to enter a timestamp is the wrong trade. It can be corrected later (SAFE-08).
         */
        post: operations["log_injection_form_emergency_injection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Process is up. Returns nothing else, by design.
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Dependencies are reachable. Returns nothing else, by design.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_confirm_csv_route_api_v1_labs_imports_csv_confirm_post */
        Body_confirm_csv_route_api_v1_labs_imports_csv_confirm_post: {
            /**
             * Analyte Map Json
             * @default {}
             */
            analyte_map_json: string;
            /** Expected Sha256 */
            expected_sha256: string;
            /** File */
            file: string;
            /** Mapping Json */
            mapping_json: string;
            /**
             * Report Local
             * Format: date-time
             */
            report_local: string;
            /**
             * Specimen Local
             * Format: date-time
             */
            specimen_local: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** Body_confirm_import_route_api_v1_integrations_garmin_imports_confirm_post */
        Body_confirm_import_route_api_v1_integrations_garmin_imports_confirm_post: {
            /** Expected Sha256 */
            expected_sha256: string;
            /** File */
            file: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** Body_log_injection_form_emergency_injection_post */
        Body_log_injection_form_emergency_injection_post: {
            /** Amount */
            amount: string;
            /**
             * Injected By
             * @default
             */
            injected_by: string;
            /**
             * Injection Site
             * @default
             */
            injection_site: string;
            /** Medication Id */
            medication_id: string;
        };
        /** Body_preview_csv_api_v1_labs_imports_csv_preview_post */
        Body_preview_csv_api_v1_labs_imports_csv_preview_post: {
            /**
             * Analyte Map Json
             * @default {}
             */
            analyte_map_json: string;
            /** File */
            file: string;
            /** Mapping Json */
            mapping_json: string;
            /**
             * Report Local
             * Format: date-time
             */
            report_local: string;
            /**
             * Specimen Local
             * Format: date-time
             */
            specimen_local: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** Body_preview_import_api_v1_integrations_garmin_imports_preview_post */
        Body_preview_import_api_v1_integrations_garmin_imports_preview_post: {
            /** File */
            file: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** Body_upload_lab_document_api_v1_labs_documents_post */
        Body_upload_lab_document_api_v1_labs_documents_post: {
            /** File */
            file: string;
        };
        /**
         * ConfirmationState
         * @description Why this record is trusted. Immutable except through a correction (SAFE-14).
         * @enum {string}
         */
        ConfirmationState: "direct" | "confirmed_from_draft" | "provider_imported";
        /**
         * CorrectionIn
         * @description A correction supersedes; it never overwrites (SAFE-08).
         */
        CorrectionIn: {
            /** Changes */
            changes?: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
        };
        /** DiaryIn */
        DiaryIn: {
            /**
             * Is Sensitive
             * @default false
             */
            is_sensitive: boolean;
            /** Tags */
            tags?: string | null;
            /** Text */
            text: string;
            time: components["schemas"]["EventTimeIn"];
        };
        /** DiaryOut */
        DiaryOut: {
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Sensitive */
            is_sensitive: boolean;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Tags */
            tags: string | null;
            /** Text */
            text: string;
            time: components["schemas"]["EventTimeOut"];
        };
        /**
         * DoseCategory
         * @description Why this dose was taken. Plan section 3.
         * @enum {string}
         */
        DoseCategory: "scheduled" | "late" | "replacement" | "stress" | "taper" | "emergency";
        /** DoseIn */
        DoseIn: {
            /** Amount */
            amount: number | string;
            /** @default scheduled */
            category: components["schemas"]["DoseCategory"];
            /** Episode Id */
            episode_id?: string | null;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Notes */
            notes?: string | null;
            /** @default oral */
            route: components["schemas"]["Route"];
            /** Slot Id */
            slot_id?: string | null;
            time: components["schemas"]["EventTimeIn"];
            unit: components["schemas"]["DoseUnit"];
        };
        /** DoseOut */
        DoseOut: {
            /** Amount */
            amount: string;
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            dose_category: components["schemas"]["DoseCategory"];
            /** Episode Id */
            episode_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Medication Name */
            medication_name: string;
            /** Notes */
            notes: string | null;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Regimen Version Id */
            regimen_version_id: string | null;
            route: components["schemas"]["Route"];
            /** Slot Id */
            slot_id: string | null;
            time: components["schemas"]["EventTimeOut"];
            unit: components["schemas"]["DoseUnit"];
        };
        /** DoseSlotIn */
        DoseSlotIn: {
            /** Amount */
            amount: number | string;
            /** Condition */
            condition?: string | null;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** @default oral */
            route: components["schemas"]["Route"];
            /**
             * Scheduled Local Time
             * Format: time
             */
            scheduled_local_time: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            unit: components["schemas"]["DoseUnit"];
        };
        /** DoseSlotOut */
        DoseSlotOut: {
            /** Amount */
            amount: string;
            /**
             * Category
             * @default plan
             * @constant
             */
            category: "plan";
            /** Condition */
            condition: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Medication Name */
            medication_name: string;
            route: components["schemas"]["Route"];
            /**
             * Scheduled Local Time
             * Format: time
             */
            scheduled_local_time: string;
            /** Sort Order */
            sort_order: number;
            unit: components["schemas"]["DoseUnit"];
        };
        /**
         * DoseUnit
         * @enum {string}
         */
        DoseUnit: "mg" | "mcg" | "ml" | "tablet";
        /** EpisodeIn */
        EpisodeIn: {
            /** Ended At */
            ended_at?: string | null;
            /** Highest Temperature C */
            highest_temperature_c?: number | string | null;
            /** Illness Description */
            illness_description?: string | null;
            /** Notes */
            notes?: string | null;
            severity?: components["schemas"]["EpisodeSeverity"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Timezone */
            timezone: string;
            /** Trigger */
            trigger: string;
        };
        /** EpisodeOut */
        EpisodeOut: {
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            /**
             * Dose Count
             * @default 0
             */
            dose_count: number;
            /** Ended At */
            ended_at: string | null;
            /** Highest Temperature C */
            highest_temperature_c: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Illness Description */
            illness_description: string | null;
            /** Notes */
            notes: string | null;
            /** Outcome */
            outcome: string | null;
            /** Recovery Notes */
            recovery_notes: string | null;
            severity: components["schemas"]["EpisodeSeverity"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["EpisodeStatus"];
            /**
             * Symptom Count
             * @default 0
             */
            symptom_count: number;
            /** Timezone */
            timezone: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * EpisodeSeverity
         * @enum {string}
         */
        EpisodeSeverity: "mild" | "moderate" | "severe";
        /**
         * EpisodeStatus
         * @enum {string}
         */
        EpisodeStatus: "open" | "resolved" | "escalated";
        /** EpisodeUpdate */
        EpisodeUpdate: {
            /** Ended At */
            ended_at?: string | null;
            /** Highest Temperature C */
            highest_temperature_c?: number | string | null;
            /** Illness Description */
            illness_description?: string | null;
            /** Notes */
            notes?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Recovery Notes */
            recovery_notes?: string | null;
            severity?: components["schemas"]["EpisodeSeverity"] | null;
            status?: components["schemas"]["EpisodeStatus"] | null;
        };
        /**
         * EventTimeIn
         * @description When something happened, as the owner experienced it.
         */
        EventTimeIn: {
            /**
             * Fold
             * @description Only for a local time repeated by a DST fall-back. 0 selects the first occurrence, 1 the second. Omitting it on an ambiguous time is an error rather than a guess.
             */
            fold?: number | null;
            /**
             * Local Time
             * Format: date-time
             * @description Naive local wall time, e.g. 2026-03-29T07:08:00
             */
            local_time: string;
            /**
             * Timezone
             * @description IANA zone, e.g. Europe/London
             */
            timezone: string;
        };
        /** EventTimeOut */
        EventTimeOut: {
            /**
             * Local Time
             * Format: date-time
             */
            local_time: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Timezone */
            timezone: string;
            /** Utc Offset Minutes */
            utc_offset_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InjectionIn
         * @description Emergency injection. Only the clinical essentials are required (SAFE-23).
         */
        InjectionIn: {
            /** Amount */
            amount: number | string;
            /** Contact Notified */
            contact_notified?: string | null;
            /** Emergency Services Called */
            emergency_services_called?: boolean | null;
            /** Episode Id */
            episode_id?: string | null;
            /** Injected By */
            injected_by?: string | null;
            /** Injection Site */
            injection_site?: string | null;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Reason */
            reason?: string | null;
            /** Response */
            response?: string | null;
            /** @default intramuscular */
            route: components["schemas"]["Route"];
            time: components["schemas"]["EventTimeIn"];
            /** Transported To Hospital */
            transported_to_hospital?: boolean | null;
            /** @default mg */
            unit: components["schemas"]["DoseUnit"];
        };
        /** InjectionOut */
        InjectionOut: {
            /** Amount */
            amount: string;
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            /** Emergency Services Called */
            emergency_services_called: boolean | null;
            /** Episode Id */
            episode_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Injected By */
            injected_by: string | null;
            /** Injection Site */
            injection_site: string | null;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Reason */
            reason: string | null;
            /** Response */
            response: string | null;
            /** Route */
            route: string;
            time: components["schemas"]["EventTimeOut"];
            /** Transported To Hospital */
            transported_to_hospital: boolean | null;
            /** Unit */
            unit: string;
        };
        /**
         * InstructionCategory
         * @enum {string}
         */
        InstructionCategory: "illness" | "procedure" | "exercise" | "emergency" | "general";
        /** InstructionIn */
        InstructionIn: {
            /** Authored By */
            authored_by: string;
            /**
             * Authored On
             * Format: date
             */
            authored_on: string;
            /** Body */
            body: string;
            category: components["schemas"]["InstructionCategory"];
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Title */
            title: string;
        };
        /** InstructionOut */
        InstructionOut: {
            /** Authored By */
            authored_by: string;
            /**
             * Authored On
             * Format: date
             */
            authored_on: string;
            /** Body */
            body: string;
            /**
             * Category
             * @default plan
             * @constant
             */
            category: "plan";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instruction_category: components["schemas"]["InstructionCategory"];
            /** Sort Order */
            sort_order: number;
            /** Title */
            title: string;
        };
        /**
         * LifeEventCategory
         * @description Context that helps explain a pattern without asserting it caused anything.
         * @enum {string}
         */
        LifeEventCategory: "travel" | "illness" | "work" | "exercise" | "sleep_disruption" | "stress" | "medical_appointment" | "other";
        /** LifeEventIn */
        LifeEventIn: {
            category: components["schemas"]["LifeEventCategory"];
            /** Description */
            description?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Is Sensitive
             * @default false
             */
            is_sensitive: boolean;
            time: components["schemas"]["EventTimeIn"];
            /** Title */
            title: string;
        };
        /** LifeEventOut */
        LifeEventOut: {
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            life_category: components["schemas"]["LifeEventCategory"];
            provenance: components["schemas"]["ProvenanceOut"];
            time: components["schemas"]["EventTimeOut"];
            /** Title */
            title: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Default Timezone */
            default_timezone: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
        };
        /** ManualLabPanelIn */
        ManualLabPanelIn: {
            /** Accession Id */
            accession_id?: string | null;
            /** Laboratory Name */
            laboratory_name?: string | null;
            /** Report Status */
            report_status?: string | null;
            report_time: components["schemas"]["EventTimeIn"];
            /** Results */
            results: components["schemas"]["ManualLabResultIn"][];
            specimen_time: components["schemas"]["EventTimeIn"];
            /** Specimen Type */
            specimen_type?: string | null;
        };
        /** ManualLabResultIn */
        ManualLabResultIn: {
            /** Abnormal Flag */
            abnormal_flag?: string | null;
            /** Analyte Name */
            analyte_name: string;
            /** Normalized Analyte Code */
            normalized_analyte_code?: string | null;
            /** Original Reference Range */
            original_reference_range?: string | null;
            /** Original Unit */
            original_unit?: string | null;
            /** Original Value */
            original_value?: string | null;
            /** Qualitative Result */
            qualitative_result?: string | null;
        };
        /** MedicationIn */
        MedicationIn: {
            /** Active From */
            active_from?: string | null;
            /** Active To */
            active_to?: string | null;
            /** @default oral */
            default_route: components["schemas"]["Route"];
            default_unit: components["schemas"]["DoseUnit"];
            /** Formulation */
            formulation?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Strength */
            strength?: number | string | null;
            /** Strength Unit */
            strength_unit?: string | null;
        };
        /** MedicationOut */
        MedicationOut: {
            /** Active From */
            active_from: string | null;
            /** Active To */
            active_to: string | null;
            /**
             * Category
             * @default plan
             * @constant
             */
            category: "plan";
            default_route: components["schemas"]["Route"];
            default_unit: components["schemas"]["DoseUnit"];
            /** Formulation */
            formulation: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            /** Strength */
            strength: string | null;
            /** Strength Unit */
            strength_unit: string | null;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PlanComparisonDay
         * @description A day compared against the plan in force on that day.
         *
         *     ``missing`` slots are *derived*, not stored: no zero-dose row is ever written
         *     (SAFE-10).
         */
        PlanComparisonDay: {
            /** Actual Total */
            actual_total: string | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Metric Definition */
            metric_definition: string;
            /** Missed Slots */
            missed_slots: number;
            /** Planned Total */
            planned_total: string | null;
            /** Regimen Version Id */
            regimen_version_id: string | null;
            /** Regimen Version Label */
            regimen_version_label: string | null;
            /** Slots */
            slots: components["schemas"]["PlanComparisonSlot"][];
            /** Timezone */
            timezone: string;
            /** Unplanned Doses */
            unplanned_doses: number;
        };
        /** PlanComparisonSlot */
        PlanComparisonSlot: {
            /** Actual Amount */
            actual_amount: string | null;
            /** Actual Local Time */
            actual_local_time: string | null;
            /** Dose Id */
            dose_id: string | null;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Medication Name */
            medication_name: string;
            /** Minutes From Scheduled */
            minutes_from_scheduled: number | null;
            /** Planned Amount */
            planned_amount: string | null;
            route: components["schemas"]["Route"];
            /** Scheduled Local Time */
            scheduled_local_time: string | null;
            /** Slot Id */
            slot_id: string | null;
            /** Status */
            status: string;
            unit: components["schemas"]["DoseUnit"];
        };
        /**
         * ProvenanceOut
         * @description How this record came to exist, and whether it has been corrected.
         */
        ProvenanceOut: {
            confirmation_state: components["schemas"]["ConfirmationState"];
            /** Correction Reason */
            correction_reason?: string | null;
            /**
             * Is Correction
             * @default false
             */
            is_correction: boolean;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            source_type: components["schemas"]["SourceType"];
            /** Supersedes Id */
            supersedes_id?: string | null;
        };
        /**
         * RegimenApprovalIn
         * @description Approval is a human act with provenance (SAFE-16). None of this is optional.
         */
        RegimenApprovalIn: {
            /**
             * Approval Source
             * @description Letter, consultation, portal message
             */
            approval_source: string;
            /** Approved At */
            approved_at?: string | null;
            /**
             * Approved By
             * @description Clinician name or role
             */
            approved_by: string;
            /** Source Document Checksum */
            source_document_checksum?: string | null;
        };
        /**
         * RegimenStatus
         * @description Only a human can move a version to ``APPROVED`` (SAFE-16).
         * @enum {string}
         */
        RegimenStatus: "draft" | "approved" | "retired";
        /** RegimenVersionIn */
        RegimenVersionIn: {
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
            /** Instructions */
            instructions?: components["schemas"]["InstructionIn"][];
            /** Notes */
            notes?: string | null;
            /** Slots */
            slots?: components["schemas"]["DoseSlotIn"][];
            /** Version Label */
            version_label: string;
        };
        /** RegimenVersionOut */
        RegimenVersionOut: {
            /** Approval Source */
            approval_source: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
            /**
             * Category
             * @default plan
             * @constant
             */
            category: "plan";
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            /** Effective To */
            effective_to: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instructions */
            instructions?: components["schemas"]["InstructionOut"][];
            /** Notes */
            notes: string | null;
            /** Retired At */
            retired_at: string | null;
            /** Slots */
            slots?: components["schemas"]["DoseSlotOut"][];
            status: components["schemas"]["RegimenStatus"];
            /** Version Label */
            version_label: string;
        };
        /**
         * Route
         * @enum {string}
         */
        Route: "oral" | "intramuscular" | "subcutaneous" | "intravenous";
        /**
         * SourceType
         * @description How a record entered the system. Never inferred (SAFE-14).
         * @enum {string}
         */
        SourceType: "web" | "telegram" | "csv_import" | "file_import" | "provider" | "migration";
        /** SymptomIn */
        SymptomIn: {
            /** Body Area */
            body_area?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Episode Id */
            episode_id?: string | null;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Severity */
            severity?: number | null;
            time: components["schemas"]["EventTimeIn"];
        };
        /** SymptomOut */
        SymptomOut: {
            /** Body Area */
            body_area: string | null;
            /**
             * Category
             * @default fact
             * @constant
             */
            category: "fact";
            /** Episode Id */
            episode_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
            provenance: components["schemas"]["ProvenanceOut"];
            /** Severity */
            severity: number | null;
            time: components["schemas"]["EventTimeOut"];
        };
        /**
         * TimelineItem
         * @description One entry on the unified timeline.
         *
         *     ``category`` is per item, never per collection: the timeline mixes facts and plan
         *     context, and SAFE-02 requires each to say which it is.
         */
        TimelineItem: {
            /**
             * Category
             * @enum {string}
             */
            category: "fact" | "plan" | "ai";
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Sensitive
             * @default false
             */
            is_sensitive: boolean;
            provenance?: components["schemas"]["ProvenanceOut"] | null;
            /** Summary */
            summary: string;
            time: components["schemas"]["EventTimeOut"];
        };
        /** TimelinePage */
        TimelinePage: {
            /** Items */
            items: components["schemas"]["TimelineItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhoAmI */
        WhoAmI: {
            /** Csrf Token */
            csrf_token: string;
            /** Default Timezone */
            default_timezone: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_everywhere_api_v1_auth_logout_everywhere_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diary_api_v1_diary_events_get: {
        parameters: {
            query?: {
                /** @description Sensitive entries are excluded from default views (T7). */
                include_sensitive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_diary_api_v1_diary_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_doses_api_v1_doses_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Include corrected-away versions. Off by default so totals are correct. */
                include_superseded?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dose_api_v1_doses_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_comparison_api_v1_doses_plan_comparison_get: {
        parameters: {
            query: {
                /** @description Local calendar day to compare */
                day: string;
                /** @description IANA zone; defaults to owner setting */
                timezone?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanComparisonDay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_dose_api_v1_doses__dose_id__correct_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                dose_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_injections_api_v1_emergency_injections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_injection_api_v1_emergency_injections_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_v1_exports_post: {
        parameters: {
            query?: {
                /** @description AI analysis is excluded by default (SAFE-07). Opt in explicitly. */
                include_ai?: boolean;
                include_sensitive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_route_api_v1_integrations_garmin_imports_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_confirm_import_route_api_v1_integrations_garmin_imports_confirm_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_v1_integrations_garmin_imports_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_api_v1_integrations_garmin_imports_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_lab_document_api_v1_labs_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_lab_document_api_v1_labs_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lab_document_api_v1_labs_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lab_document_api_v1_labs_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_lab_document_api_v1_labs_documents__document_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lab_document_extraction_api_v1_labs_documents__document_id__extraction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_csv_route_api_v1_labs_imports_csv_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_confirm_csv_route_api_v1_labs_imports_csv_confirm_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_csv_api_v1_labs_imports_csv_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_csv_api_v1_labs_imports_csv_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_lab_api_v1_labs_manual_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualLabPanelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_life_events_api_v1_life_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_life_event_api_v1_life_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LifeEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifeEventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_medications_api_v1_medications_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_medication_api_v1_medications_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regimens_api_v1_regimens_get: {
        parameters: {
            query?: {
                status_filter?: components["schemas"]["RegimenStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimenVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_regimen_api_v1_regimens_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegimenVersionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimenVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_regimen_api_v1_regimens_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimenVersionOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_regimen_api_v1_regimens__version_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegimenApprovalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimenVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_regimens_api_v1_regimens__version_id__diff__other_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                other_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_regimen_api_v1_regimens__version_id__retire_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                version_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimenVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_episodes_api_v1_stress_episodes_get: {
        parameters: {
            query?: {
                open_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_episode_api_v1_stress_episodes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_episode_api_v1_stress_episodes__episode_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                episode_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_symptoms_api_v1_symptoms_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_symptom_api_v1_symptoms_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymptomIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_symptom_api_v1_symptoms__event_id__correct_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_timeline_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Comma-separated event types */
                types?: string | null;
                timezone?: string | null;
                local_date_from?: string | null;
                local_date_to?: string | null;
                include_sensitive?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelinePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emergency_page_emergency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_injection_form_emergency_injection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                hc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_log_injection_form_emergency_injection_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
