"""garmin file imports

Revision ID: 71a1dfc8cb3b
Revises: c862f3a1d901
Create Date: 2026-08-09 12:35:07.727715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71a1dfc8cb3b"
down_revision: Union[str, Sequence[str], None] = "c862f3a1d901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "garmin_import_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=False),
        sa.Column("source_media_type", sa.String(length=100), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_byte_size", sa.Integer(), nullable=False),
        sa.Column("source_payload", sa.LargeBinary(), nullable=False),
        sa.Column("source_members", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sdk_profile_version", sa.String(length=32), nullable=False),
        sa.Column("observed_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("device_attributions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_byte_size = octet_length(source_payload)",
            name=op.f("ck_garmin_import_batch_garmin_batch_size_matches"),
        ),
        sa.CheckConstraint(
            "source_byte_size > 0", name=op.f("ck_garmin_import_batch_garmin_batch_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_garmin_import_batch_owner_id_owner"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garmin_import_batch")),
        sa.UniqueConstraint("owner_id", "source_sha256", name="uq_garmin_batch_owner_checksum"),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_import_batch_owner_id"),
        "garmin_import_batch",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_table(
        "garmin_activity_event",
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sport", sa.String(length=80), nullable=False),
        sa.Column("sub_sport", sa.String(length=80), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("elapsed_seconds", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("distance_m", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("average_heart_rate", sa.Integer(), nullable=True),
        sa.Column("maximum_heart_rate", sa.Integer(), nullable=True),
        sa.Column("source_notes", sa.Text(), nullable=True),
        sa.Column("garmin_import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("garmin_source_member", sa.String(length=500), nullable=False),
        sa.Column("garmin_manufacturer", sa.String(length=120), nullable=False),
        sa.Column("garmin_product_name", sa.String(length=200), nullable=True),
        sa.Column("garmin_device_serial_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "average_heart_rate IS NULL OR average_heart_rate BETWEEN 20 AND 260",
            name=op.f("ck_garmin_activity_event_average_hr_plausible"),
        ),
        sa.CheckConstraint(
            "calories IS NULL OR calories >= 0",
            name=op.f("ck_garmin_activity_event_calories_nonnegative"),
        ),
        sa.CheckConstraint(
            "distance_m IS NULL OR distance_m >= 0",
            name=op.f("ck_garmin_activity_event_distance_nonnegative"),
        ),
        sa.CheckConstraint(
            "elapsed_seconds IS NULL OR elapsed_seconds >= 0",
            name=op.f("ck_garmin_activity_event_elapsed_nonnegative"),
        ),
        sa.CheckConstraint(
            "ended_at >= occurred_at",
            name=op.f("ck_garmin_activity_event_activity_interval_ordered"),
        ),
        sa.CheckConstraint(
            "maximum_heart_rate IS NULL OR maximum_heart_rate BETWEEN 20 AND 260",
            name=op.f("ck_garmin_activity_event_maximum_hr_plausible"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at",
            name=op.f("ck_garmin_activity_event_recorded_after_occurred"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_garmin_activity_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_garmin_activity_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["garmin_import_batch_id"],
            ["fact.garmin_import_batch.id"],
            name=op.f("fk_garmin_activity_event_garmin_import_batch_id_garmin_import_batch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_garmin_activity_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.garmin_activity_event.id"],
            name=op.f("fk_garmin_activity_event_supersedes_id_garmin_activity_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garmin_activity_event")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_activity_event_garmin_import_batch_id"),
        "garmin_activity_event",
        ["garmin_import_batch_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_activity_event_owner_id"),
        "garmin_activity_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "ix_garmin_activity_event_occurred_at",
        "garmin_activity_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "ix_garmin_activity_sport_time",
        "garmin_activity_event",
        ["sport", "occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_garmin_activity_event_provider_identity",
        "garmin_activity_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_garmin_activity_event_supersedes_once",
        "garmin_activity_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "garmin_metric_event",
        sa.Column("metric_type", sa.String(length=48), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("period_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("garmin_field_name", sa.String(length=120), nullable=False),
        sa.Column("garmin_import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("garmin_source_member", sa.String(length=500), nullable=False),
        sa.Column("garmin_manufacturer", sa.String(length=120), nullable=False),
        sa.Column("garmin_product_name", sa.String(length=200), nullable=True),
        sa.Column("garmin_device_serial_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "period_end_at IS NULL OR period_end_at >= occurred_at",
            name=op.f("ck_garmin_metric_event_period_ordered"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at",
            name=op.f("ck_garmin_metric_event_recorded_after_occurred"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_garmin_metric_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_garmin_metric_event_offset_within_real_range"),
        ),
        sa.CheckConstraint("value >= 0", name=op.f("ck_garmin_metric_event_metric_nonnegative")),
        sa.ForeignKeyConstraint(
            ["garmin_import_batch_id"],
            ["fact.garmin_import_batch.id"],
            name=op.f("fk_garmin_metric_event_garmin_import_batch_id_garmin_import_batch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_garmin_metric_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.garmin_metric_event.id"],
            name=op.f("fk_garmin_metric_event_supersedes_id_garmin_metric_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garmin_metric_event")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_metric_event_garmin_import_batch_id"),
        "garmin_metric_event",
        ["garmin_import_batch_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_metric_event_owner_id"),
        "garmin_metric_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "ix_garmin_metric_event_occurred_at",
        "garmin_metric_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_garmin_metric_event_provider_identity",
        "garmin_metric_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_garmin_metric_event_supersedes_once",
        "garmin_metric_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "garmin_sleep_event",
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("overall_sleep_score", sa.Integer(), nullable=True),
        sa.Column("stage_count", sa.Integer(), nullable=False),
        sa.Column("garmin_import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("garmin_source_member", sa.String(length=500), nullable=False),
        sa.Column("garmin_manufacturer", sa.String(length=120), nullable=False),
        sa.Column("garmin_product_name", sa.String(length=200), nullable=True),
        sa.Column("garmin_device_serial_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "ended_at > occurred_at", name=op.f("ck_garmin_sleep_event_sleep_interval_ordered")
        ),
        sa.CheckConstraint(
            "overall_sleep_score IS NULL OR overall_sleep_score BETWEEN 0 AND 100",
            name=op.f("ck_garmin_sleep_event_sleep_score_range"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_garmin_sleep_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "stage_count >= 2", name=op.f("ck_garmin_sleep_event_sleep_has_explicit_bounds")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_garmin_sleep_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_garmin_sleep_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["garmin_import_batch_id"],
            ["fact.garmin_import_batch.id"],
            name=op.f("fk_garmin_sleep_event_garmin_import_batch_id_garmin_import_batch"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_garmin_sleep_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.garmin_sleep_event.id"],
            name=op.f("fk_garmin_sleep_event_supersedes_id_garmin_sleep_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_garmin_sleep_event")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_sleep_event_garmin_import_batch_id"),
        "garmin_sleep_event",
        ["garmin_import_batch_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_garmin_sleep_event_owner_id"),
        "garmin_sleep_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "ix_garmin_sleep_event_occurred_at",
        "garmin_sleep_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_garmin_sleep_event_provider_identity",
        "garmin_sleep_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_garmin_sleep_event_supersedes_once",
        "garmin_sleep_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    # Repair names emitted with a duplicated naming-convention prefix by the two
    # preceding migrations. The expressions do not change; this makes a freshly
    # migrated database match model metadata and keeps future autogeneration clean.
    op.drop_constraint(
        op.f("ck_integration_credential_ck_integration_credential_cre_6a71"),
        "integration_credential",
        schema="identity",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_integration_credential_ck_integration_credential_cre_bd96"),
        "integration_credential",
        schema="identity",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_integration_credential_credential_ciphertext_has_tag"),
        "integration_credential",
        "octet_length(ciphertext) >= 16",
        schema="identity",
    )
    op.create_check_constraint(
        op.f("ck_integration_credential_credential_nonce_length"),
        "integration_credential",
        "octet_length(nonce) = 12",
        schema="identity",
    )
    op.drop_constraint(
        op.f("ck_job_ck_job_attempt_count_nonnegative"),
        "job",
        schema="ops",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_job_ck_job_max_attempts_bounded"), "job", schema="ops", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_job_attempt_count_nonnegative"),
        "job",
        "attempt_count >= 0",
        schema="ops",
    )
    op.create_check_constraint(
        op.f("ck_job_max_attempts_bounded"),
        "job",
        "max_attempts BETWEEN 1 AND 100",
        schema="ops",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_job_max_attempts_bounded"), "job", schema="ops", type_="check")
    op.drop_constraint(op.f("ck_job_attempt_count_nonnegative"), "job", schema="ops", type_="check")
    op.create_check_constraint(
        op.f("ck_job_ck_job_max_attempts_bounded"),
        "job",
        "max_attempts >= 1 AND max_attempts <= 100",
        schema="ops",
    )
    op.create_check_constraint(
        op.f("ck_job_ck_job_attempt_count_nonnegative"),
        "job",
        "attempt_count >= 0",
        schema="ops",
    )
    op.drop_constraint(
        op.f("ck_integration_credential_credential_nonce_length"),
        "integration_credential",
        schema="identity",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_integration_credential_credential_ciphertext_has_tag"),
        "integration_credential",
        schema="identity",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_integration_credential_ck_integration_credential_cre_bd96"),
        "integration_credential",
        "octet_length(nonce) = 12",
        schema="identity",
    )
    op.create_check_constraint(
        op.f("ck_integration_credential_ck_integration_credential_cre_6a71"),
        "integration_credential",
        "octet_length(ciphertext) >= 16",
        schema="identity",
    )
    op.drop_index(
        "uq_garmin_sleep_event_supersedes_once",
        table_name="garmin_sleep_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_garmin_sleep_event_provider_identity",
        table_name="garmin_sleep_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_garmin_sleep_event_occurred_at", table_name="garmin_sleep_event", schema="fact"
    )
    op.drop_index(
        op.f("ix_fact_garmin_sleep_event_owner_id"), table_name="garmin_sleep_event", schema="fact"
    )
    op.drop_index(
        op.f("ix_fact_garmin_sleep_event_garmin_import_batch_id"),
        table_name="garmin_sleep_event",
        schema="fact",
    )
    op.drop_table("garmin_sleep_event", schema="fact")
    op.drop_index(
        "uq_garmin_metric_event_supersedes_once",
        table_name="garmin_metric_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_garmin_metric_event_provider_identity",
        table_name="garmin_metric_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_garmin_metric_event_occurred_at", table_name="garmin_metric_event", schema="fact"
    )
    op.drop_index(
        op.f("ix_fact_garmin_metric_event_owner_id"),
        table_name="garmin_metric_event",
        schema="fact",
    )
    op.drop_index(
        op.f("ix_fact_garmin_metric_event_garmin_import_batch_id"),
        table_name="garmin_metric_event",
        schema="fact",
    )
    op.drop_table("garmin_metric_event", schema="fact")
    op.drop_index(
        "uq_garmin_activity_event_supersedes_once",
        table_name="garmin_activity_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_garmin_activity_event_provider_identity",
        table_name="garmin_activity_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_garmin_activity_sport_time", table_name="garmin_activity_event", schema="fact"
    )
    op.drop_index(
        "ix_garmin_activity_event_occurred_at", table_name="garmin_activity_event", schema="fact"
    )
    op.drop_index(
        op.f("ix_fact_garmin_activity_event_owner_id"),
        table_name="garmin_activity_event",
        schema="fact",
    )
    op.drop_index(
        op.f("ix_fact_garmin_activity_event_garmin_import_batch_id"),
        table_name="garmin_activity_event",
        schema="fact",
    )
    op.drop_table("garmin_activity_event", schema="fact")
    op.drop_index(
        op.f("ix_fact_garmin_import_batch_owner_id"),
        table_name="garmin_import_batch",
        schema="fact",
    )
    op.drop_table("garmin_import_batch", schema="fact")
    # ### end Alembic commands ###
