"""phase 1 schema

Revision ID: d53209775117
Revises:
Create Date: 2026-08-08 20:31:55.261887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d53209775117"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_type", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("range_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("range_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("computed_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("model_digest", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analysis")),
        schema="ai",
    )
    op.create_index(
        op.f("ix_ai_ai_analysis_owner_id"), "ai_analysis", ["owner_id"], unique=False, schema="ai"
    )
    op.create_table(
        "extraction_draft",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("model_digest", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_event_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_draft")),
        schema="ai",
    )
    op.create_index(
        op.f("ix_ai_extraction_draft_owner_id"),
        "extraction_draft",
        ["owner_id"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_draft_owner_state", "extraction_draft", ["owner_id", "state"], unique=False, schema="ai"
    )
    op.create_index(
        "uq_draft_provider_message",
        "extraction_draft",
        ["source", "provider_message_id"],
        unique=True,
        schema="ai",
    )
    op.create_table(
        "owner",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("default_timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_owner")),
        sa.UniqueConstraint("email", name=op.f("uq_owner_email")),
        schema="identity",
    )
    op.create_table(
        "audit_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("change_summary", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_entry")),
        schema="ops",
    )
    op.create_index(
        "ix_audit_action_time", "audit_entry", ["action", "occurred_at"], unique=False, schema="ops"
    )
    op.create_index(
        op.f("ix_ops_audit_entry_action"), "audit_entry", ["action"], unique=False, schema="ops"
    )
    op.create_index(
        op.f("ix_ops_audit_entry_correlation_id"),
        "audit_entry",
        ["correlation_id"],
        unique=False,
        schema="ops",
    )
    op.create_index(
        op.f("ix_ops_audit_entry_occurred_at"),
        "audit_entry",
        ["occurred_at"],
        unique=False,
        schema="ops",
    )
    op.create_table(
        "telegram_update",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_update")),
        sa.UniqueConstraint("update_id", name=op.f("uq_telegram_update_update_id")),
        schema="ops",
    )
    op.create_index(
        op.f("ix_ops_telegram_update_chat_id"),
        "telegram_update",
        ["chat_id"],
        unique=False,
        schema="ops",
    )
    op.create_table(
        "diary_event",
        sa.Column("text", sa.String(length=10000), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_diary_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_diary_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_diary_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_diary_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.diary_event.id"],
            name=op.f("fk_diary_event_supersedes_id_diary_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diary_event")),
        schema="fact",
    )
    op.create_index(
        "ix_diary_event_occurred_at", "diary_event", ["occurred_at"], unique=False, schema="fact"
    )
    op.create_index(
        op.f("ix_fact_diary_event_owner_id"),
        "diary_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_diary_event_provider_identity",
        "diary_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_diary_event_supersedes_once",
        "diary_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "life_event",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= occurred_at",
            name=op.f("ck_life_event_interval_ordered"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_life_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_life_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_life_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_life_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.life_event.id"],
            name=op.f("fk_life_event_supersedes_id_life_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_life_event")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_life_event_owner_id"), "life_event", ["owner_id"], unique=False, schema="fact"
    )
    op.create_index(
        "ix_life_event_occurred_at", "life_event", ["occurred_at"], unique=False, schema="fact"
    )
    op.create_index(
        "uq_life_event_provider_identity",
        "life_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_life_event_supersedes_once",
        "life_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "stress_episode",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("highest_temperature_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("illness_description", sa.String(length=500), nullable=True),
        sa.Column("recovery_notes", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status <> 'resolved' OR ended_at IS NOT NULL",
            name=op.f("ck_stress_episode_resolved_requires_end"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_stress_episode_interval_ordered"),
        ),
        sa.CheckConstraint(
            "highest_temperature_c IS NULL OR highest_temperature_c BETWEEN 25 AND 45",
            name=op.f("ck_stress_episode_temperature_plausible"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_stress_episode_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stress_episode")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_stress_episode_owner_id"),
        "stress_episode",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_stress_episode_started_at"),
        "stress_episode",
        ["started_at"],
        unique=False,
        schema="fact",
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_auth_session_owner_id_owner"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_session_token_hash")),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_auth_session_owner_id"),
        "auth_session",
        ["owner_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "medication",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("formulation", sa.String(length=120), nullable=True),
        sa.Column("strength", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("strength_unit", sa.String(length=16), nullable=True),
        sa.Column("default_unit", sa.String(length=16), nullable=False),
        sa.Column("default_route", sa.String(length=24), nullable=False),
        sa.Column("active_from", sa.Date(), nullable=True),
        sa.Column("active_to", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "active_to IS NULL OR active_from IS NULL OR active_to >= active_from",
            name=op.f("ck_medication_active_range_ordered"),
        ),
        sa.CheckConstraint(
            "strength IS NULL OR strength > 0", name=op.f("ck_medication_strength_positive")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_medication_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication")),
        sa.UniqueConstraint("owner_id", "normalized_name", "strength", name="unique_per_owner"),
        schema="plan",
    )
    op.create_index(
        op.f("ix_plan_medication_owner_id"), "medication", ["owner_id"], unique=False, schema="plan"
    )
    op.create_table(
        "regimen_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version_label", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.DateTime(), nullable=False),
        sa.Column("effective_to", sa.DateTime(), nullable=True),
        sa.Column("effective_period", postgresql.TSRANGE(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("approval_source", sa.String(length=200), nullable=True),
        sa.Column("source_document_checksum", sa.String(length=128), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("owner_id"), "="),
            (sa.column("effective_period"), "&&"),
            where=sa.text("status = 'approved'"),
            using="gist",
            name="approved_versions_do_not_overlap",
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR (approved_at IS NOT NULL AND approved_by IS NOT NULL)",
            name=op.f("ck_regimen_version_approved_requires_provenance"),
        ),
        sa.CheckConstraint(
            "status <> 'retired' OR retired_at IS NOT NULL",
            name=op.f("ck_regimen_version_retired_requires_timestamp"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_regimen_version_effective_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_regimen_version_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regimen_version")),
        schema="plan",
    )
    op.create_index(
        op.f("ix_plan_regimen_version_owner_id"),
        "regimen_version",
        ["owner_id"],
        unique=False,
        schema="plan",
    )
    op.create_index(
        "ix_regimen_version_owner_status",
        "regimen_version",
        ["owner_id", "status"],
        unique=False,
        schema="plan",
    )
    op.create_table(
        "emergency_injection_event",
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=24), nullable=False),
        sa.Column("injection_site", sa.String(length=120), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("injected_by", sa.String(length=120), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("emergency_services_called", sa.Boolean(), nullable=True),
        sa.Column("transported_to_hospital", sa.Boolean(), nullable=True),
        sa.Column("contact_notified", sa.String(length=200), nullable=True),
        sa.Column("episode_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_emergency_injection_event_amount_positive")),
        sa.CheckConstraint(
            "recorded_at >= occurred_at",
            name=op.f("ck_emergency_injection_event_recorded_after_occurred"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_emergency_injection_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_emergency_injection_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["fact.stress_episode.id"],
            name=op.f("fk_emergency_injection_event_episode_id_stress_episode"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["plan.medication.id"],
            name=op.f("fk_emergency_injection_event_medication_id_medication"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_emergency_injection_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.emergency_injection_event.id"],
            name=op.f("fk_emergency_injection_event_supersedes_id_emergency_injection_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_injection_event")),
        schema="fact",
    )
    op.create_index(
        "ix_emergency_injection_event_occurred_at",
        "emergency_injection_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_emergency_injection_event_episode_id"),
        "emergency_injection_event",
        ["episode_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_emergency_injection_event_owner_id"),
        "emergency_injection_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_emergency_injection_event_provider_identity",
        "emergency_injection_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_emergency_injection_event_supersedes_once",
        "emergency_injection_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "symptom_event",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.SmallInteger(), nullable=True),
        sa.Column("body_area", sa.String(length=120), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("episode_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= occurred_at",
            name=op.f("ck_symptom_event_interval_ordered"),
        ),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_symptom_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity BETWEEN 0 AND 10",
            name=op.f("ck_symptom_event_severity_scale"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_symptom_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_symptom_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["fact.stress_episode.id"],
            name=op.f("fk_symptom_event_episode_id_stress_episode"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_symptom_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.symptom_event.id"],
            name=op.f("fk_symptom_event_supersedes_id_symptom_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symptom_event")),
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_symptom_event_episode_id"),
        "symptom_event",
        ["episode_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_symptom_event_owner_id"),
        "symptom_event",
        ["owner_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "ix_symptom_event_occurred_at",
        "symptom_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_symptom_event_provider_identity",
        "symptom_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_symptom_event_supersedes_once",
        "symptom_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "approved_instruction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("regimen_version_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("authored_by", sa.String(length=200), nullable=False),
        sa.Column("authored_on", sa.Date(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["regimen_version_id"],
            ["plan.regimen_version.id"],
            name=op.f("fk_approved_instruction_regimen_version_id_regimen_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_instruction")),
        schema="plan",
    )
    op.create_index(
        op.f("ix_plan_approved_instruction_regimen_version_id"),
        "approved_instruction",
        ["regimen_version_id"],
        unique=False,
        schema="plan",
    )
    op.create_table(
        "regimen_dose_slot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("regimen_version_id", sa.Uuid(), nullable=False),
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_local_time", sa.Time(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=24), nullable=False),
        sa.Column("condition", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_regimen_dose_slot_amount_positive")),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["plan.medication.id"],
            name=op.f("fk_regimen_dose_slot_medication_id_medication"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["regimen_version_id"],
            ["plan.regimen_version.id"],
            name=op.f("fk_regimen_dose_slot_regimen_version_id_regimen_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regimen_dose_slot")),
        schema="plan",
    )
    op.create_index(
        op.f("ix_plan_regimen_dose_slot_regimen_version_id"),
        "regimen_dose_slot",
        ["regimen_version_id"],
        unique=False,
        schema="plan",
    )
    op.create_index(
        "ix_slot_version_time",
        "regimen_dose_slot",
        ["regimen_version_id", "scheduled_local_time"],
        unique=False,
        schema="plan",
    )
    op.create_table(
        "dose_event",
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("route", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("regimen_version_id", sa.Uuid(), nullable=True),
        sa.Column("slot_id", sa.Uuid(), nullable=True),
        sa.Column("episode_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_dose_event_amount_positive")),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_dose_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_dose_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_dose_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["fact.stress_episode.id"],
            name=op.f("fk_dose_event_episode_id_stress_episode"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["plan.medication.id"],
            name=op.f("fk_dose_event_medication_id_medication"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identity.owner.id"],
            name=op.f("fk_dose_event_owner_id_owner"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["regimen_version_id"],
            ["plan.regimen_version.id"],
            name=op.f("fk_dose_event_regimen_version_id_regimen_version"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["plan.regimen_dose_slot.id"],
            name=op.f("fk_dose_event_slot_id_regimen_dose_slot"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.dose_event.id"],
            name=op.f("fk_dose_event_supersedes_id_dose_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dose_event")),
        schema="fact",
    )
    op.create_index(
        "ix_dose_event_occurred_at", "dose_event", ["occurred_at"], unique=False, schema="fact"
    )
    op.create_index(
        op.f("ix_fact_dose_event_episode_id"),
        "dose_event",
        ["episode_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_dose_event_medication_id"),
        "dose_event",
        ["medication_id"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        op.f("ix_fact_dose_event_owner_id"), "dose_event", ["owner_id"], unique=False, schema="fact"
    )
    op.create_index(
        "uq_dose_event_provider_identity",
        "dose_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_dose_event_supersedes_once",
        "dose_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_dose_event_supersedes_once",
        table_name="dose_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_dose_event_provider_identity",
        table_name="dose_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_fact_dose_event_owner_id"), table_name="dose_event", schema="fact")
    op.drop_index(op.f("ix_fact_dose_event_medication_id"), table_name="dose_event", schema="fact")
    op.drop_index(op.f("ix_fact_dose_event_episode_id"), table_name="dose_event", schema="fact")
    op.drop_index("ix_dose_event_occurred_at", table_name="dose_event", schema="fact")
    op.drop_table("dose_event", schema="fact")
    op.drop_index("ix_slot_version_time", table_name="regimen_dose_slot", schema="plan")
    op.drop_index(
        op.f("ix_plan_regimen_dose_slot_regimen_version_id"),
        table_name="regimen_dose_slot",
        schema="plan",
    )
    op.drop_table("regimen_dose_slot", schema="plan")
    op.drop_index(
        op.f("ix_plan_approved_instruction_regimen_version_id"),
        table_name="approved_instruction",
        schema="plan",
    )
    op.drop_table("approved_instruction", schema="plan")
    op.drop_index(
        "uq_symptom_event_supersedes_once",
        table_name="symptom_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_symptom_event_provider_identity",
        table_name="symptom_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index("ix_symptom_event_occurred_at", table_name="symptom_event", schema="fact")
    op.drop_index(op.f("ix_fact_symptom_event_owner_id"), table_name="symptom_event", schema="fact")
    op.drop_index(
        op.f("ix_fact_symptom_event_episode_id"), table_name="symptom_event", schema="fact"
    )
    op.drop_table("symptom_event", schema="fact")
    op.drop_index(
        "uq_emergency_injection_event_supersedes_once",
        table_name="emergency_injection_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_emergency_injection_event_provider_identity",
        table_name="emergency_injection_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_fact_emergency_injection_event_owner_id"),
        table_name="emergency_injection_event",
        schema="fact",
    )
    op.drop_index(
        op.f("ix_fact_emergency_injection_event_episode_id"),
        table_name="emergency_injection_event",
        schema="fact",
    )
    op.drop_index(
        "ix_emergency_injection_event_occurred_at",
        table_name="emergency_injection_event",
        schema="fact",
    )
    op.drop_table("emergency_injection_event", schema="fact")
    op.drop_index("ix_regimen_version_owner_status", table_name="regimen_version", schema="plan")
    op.drop_index(
        op.f("ix_plan_regimen_version_owner_id"), table_name="regimen_version", schema="plan"
    )
    op.drop_table("regimen_version", schema="plan")
    op.drop_index(op.f("ix_plan_medication_owner_id"), table_name="medication", schema="plan")
    op.drop_table("medication", schema="plan")
    op.drop_index(
        op.f("ix_identity_auth_session_owner_id"), table_name="auth_session", schema="identity"
    )
    op.drop_table("auth_session", schema="identity")
    op.drop_index(
        op.f("ix_fact_stress_episode_started_at"), table_name="stress_episode", schema="fact"
    )
    op.drop_index(
        op.f("ix_fact_stress_episode_owner_id"), table_name="stress_episode", schema="fact"
    )
    op.drop_table("stress_episode", schema="fact")
    op.drop_index(
        "uq_life_event_supersedes_once",
        table_name="life_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_life_event_provider_identity",
        table_name="life_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index("ix_life_event_occurred_at", table_name="life_event", schema="fact")
    op.drop_index(op.f("ix_fact_life_event_owner_id"), table_name="life_event", schema="fact")
    op.drop_table("life_event", schema="fact")
    op.drop_index(
        "uq_diary_event_supersedes_once",
        table_name="diary_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_diary_event_provider_identity",
        table_name="diary_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_fact_diary_event_owner_id"), table_name="diary_event", schema="fact")
    op.drop_index("ix_diary_event_occurred_at", table_name="diary_event", schema="fact")
    op.drop_table("diary_event", schema="fact")
    op.drop_index(
        op.f("ix_ops_telegram_update_chat_id"), table_name="telegram_update", schema="ops"
    )
    op.drop_table("telegram_update", schema="ops")
    op.drop_index(op.f("ix_ops_audit_entry_occurred_at"), table_name="audit_entry", schema="ops")
    op.drop_index(op.f("ix_ops_audit_entry_correlation_id"), table_name="audit_entry", schema="ops")
    op.drop_index(op.f("ix_ops_audit_entry_action"), table_name="audit_entry", schema="ops")
    op.drop_index("ix_audit_action_time", table_name="audit_entry", schema="ops")
    op.drop_table("audit_entry", schema="ops")
    op.drop_table("owner", schema="identity")
    op.drop_index("uq_draft_provider_message", table_name="extraction_draft", schema="ai")
    op.drop_index("ix_draft_owner_state", table_name="extraction_draft", schema="ai")
    op.drop_index(
        op.f("ix_ai_extraction_draft_owner_id"), table_name="extraction_draft", schema="ai"
    )
    op.drop_table("extraction_draft", schema="ai")
    op.drop_index(op.f("ix_ai_ai_analysis_owner_id"), table_name="ai_analysis", schema="ai")
    op.drop_table("ai_analysis", schema="ai")
    # ### end Alembic commands ###
