"""canonical event base: symptom and diary events

Revision ID: e6d69c883f49
Revises:
Create Date: 2026-08-08 20:00:34.946058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6d69c883f49"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diary_event",
        sa.Column("text", sa.String(length=10000), nullable=False),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_diary_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_diary_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_diary_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.diary_event.id"],
            name=op.f("fk_diary_event_supersedes_id_diary_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diary_event")),
        schema="fact",
    )
    op.create_index(
        "ix_diary_event_occurred_at", "diary_event", ["occurred_at"], unique=False, schema="fact"
    )
    op.create_index(
        "uq_diary_event_provider_identity",
        "diary_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_diary_event_supersedes_once",
        "diary_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.create_table(
        "symptom_event",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("severity", sa.SmallInteger(), nullable=True),
        sa.Column("body_area", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_time", sa.DateTime(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("utc_offset_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("confirmation_state", sa.String(length=32), nullable=False),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "recorded_at >= occurred_at", name=op.f("ck_symptom_event_recorded_after_occurred")
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity BETWEEN 0 AND 10",
            name=op.f("ck_symptom_event_severity_scale"),
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_symptom_event_no_self_supersede"),
        ),
        sa.CheckConstraint(
            "utc_offset_minutes BETWEEN -720 AND 840",
            name=op.f("ck_symptom_event_offset_within_real_range"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["fact.symptom_event.id"],
            name=op.f("fk_symptom_event_supersedes_id_symptom_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symptom_event")),
        schema="fact",
    )
    op.create_index(
        "ix_symptom_event_occurred_at",
        "symptom_event",
        ["occurred_at"],
        unique=False,
        schema="fact",
    )
    op.create_index(
        "uq_symptom_event_provider_identity",
        "symptom_event",
        ["source_type", "provider_id", "source_revision"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "uq_symptom_event_supersedes_once",
        "symptom_event",
        ["supersedes_id"],
        unique=True,
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_symptom_event_supersedes_once",
        table_name="symptom_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_symptom_event_provider_identity",
        table_name="symptom_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index("ix_symptom_event_occurred_at", table_name="symptom_event", schema="fact")
    op.drop_table("symptom_event", schema="fact")
    op.drop_index(
        "uq_diary_event_supersedes_once",
        table_name="diary_event",
        schema="fact",
        postgresql_where=sa.text("supersedes_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_diary_event_provider_identity",
        table_name="diary_event",
        schema="fact",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_index("ix_diary_event_occurred_at", table_name="diary_event", schema="fact")
    op.drop_table("diary_event", schema="fact")
    # ### end Alembic commands ###
