import { useMutation } from "@tanstack/react-query";
import { useState } from "react";

import { deleteAccount, disconnectIntegration, downloadPrivateExport, revokeAllSessions } from "../api/client";
import { sessionStore } from "../api/session";
import { useAuth } from "../auth/context";
import { Page } from "../components/Page";

function IntegrationControl({ provider, description }: { provider: "garmin" | "telegram"; description: string }): React.JSX.Element {
  const mutation = useMutation({ mutationFn: ({ password, deleteData }: { password: string; deleteData: boolean }) => disconnectIntegration(provider, password, deleteData) });
  function submit(event: React.SyntheticEvent<HTMLFormElement>): void { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate({ password: data.get("password") as string, deleteData: data.get("delete_data") === "on" }); }
  return <article className="settings-card"><h3>{provider === "garmin" ? "Garmin imports" : "Telegram logging"}</h3><p>{description}</p><form className="privacy-action" onSubmit={submit}><label>Current password<input name="password" type="password" required autoComplete="current-password" /></label><label className="checkbox-label"><input name="delete_data" type="checkbox" defaultChecked />Delete imported/provider-derived data as well as disconnecting</label><button type="submit" disabled={mutation.isPending}>Disconnect {provider}</button></form>{mutation.isSuccess ? <p className="success-message" role="status">Disconnected. {mutation.data.credentials_deleted} credential(s) and {mutation.data.data_rows_deleted} provider row(s) deleted.</p> : null}{mutation.isError ? <p className="error-summary" role="alert">The integration was not disconnected. Check your password.</p> : null}</article>;
}

export function SettingsPage(): React.JSX.Element {
  const { session } = useAuth();
  const [includeAi, setIncludeAi] = useState(false);
  const exportMutation = useMutation({ mutationFn: (password: string) => downloadPrivateExport(password, includeAi), onSuccess: (blob) => { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "healthcurve-export.json"; link.click(); URL.revokeObjectURL(url); } });
  const sessions = useMutation({ mutationFn: revokeAllSessions, onSuccess: () => { sessionStore.clear(); } });
  const account = useMutation({ mutationFn: ({ password, confirmation }: { password: string; confirmation: string }) => deleteAccount(password, confirmation), onSuccess: () => { sessionStore.clear(); } });

  return <Page title="Settings & privacy" description="Control access, integrations, exports, retention, and deletion without exposing stored secrets.">
    <section aria-labelledby="security-heading"><h2 id="security-heading">Account and sessions</h2><div className="settings-card"><p><strong>Signed in as:</strong> {session?.user.email}</p><p><strong>Default timezone:</strong> {session?.user.defaultTimezone}</p><button type="button" onClick={() => { sessions.mutate(); }} disabled={sessions.isPending}>Sign out every session</button>{sessions.isError ? <p className="error-summary" role="alert">Sessions could not be revoked.</p> : null}</div></section>
    <section aria-labelledby="integration-heading"><h2 id="integration-heading">Integrations</h2><p>Stored tokens are encrypted and are never displayed here.</p><div className="settings-grid"><IntegrationControl provider="garmin" description="HealthCurve retains each confirmed source export and its derived Garmin facts until you delete them." /><IntegrationControl provider="telegram" description="HealthCurve retains Telegram update IDs and outcomes for replay protection. Pending drafts may retain message text; confirmed or cancelled drafts purge that raw text. Telegram itself may retain messages under your Telegram account settings." /></div></section>
    <section aria-labelledby="export-heading"><h2 id="export-heading">Export</h2><form className="settings-card privacy-action" onSubmit={(event) => { event.preventDefault(); exportMutation.mutate(new FormData(event.currentTarget).get("password") as string); }}><p>Download facts and physician-approved plan data. Integration credentials are never included.</p><label>Current password<input name="password" type="password" required autoComplete="current-password" /></label><label className="checkbox-label"><input type="checkbox" checked={includeAi} onChange={(event) => { setIncludeAi(event.target.checked); }} />Include separately labeled AI analysis</label><button type="submit" disabled={exportMutation.isPending}>Download private export</button>{exportMutation.isError ? <p className="error-summary" role="alert">The export was not created. Check your password.</p> : null}</form></section>
    <section aria-labelledby="retention-heading"><h2 id="retention-heading">Retention, location, backups, and audit</h2><div className="settings-card"><p><strong>Location precision:</strong> Location collection is not configured; HealthCurve does not currently store your location.</p><p><strong>Backup status:</strong> Not available to the web application. Use the private backup status command and restore drill.</p><p><strong>Deletion and backups:</strong> Deletion removes live application data. Encrypted backups can retain deleted data until those backup copies reach their configured expiry.</p><p><strong>Audit retention:</strong> Structural audit entries recording deletion survive account and record deletion. They contain action metadata, not the deleted health content.</p></div></section>
    <section aria-labelledby="delete-heading"><h2 id="delete-heading">Delete account</h2><form className="settings-card privacy-action danger-zone" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); account.mutate({ password: data.get("password") as string, confirmation: data.get("confirmation") as string }); }}><p>This permanently deletes live health facts, plans, AI drafts, retained lab files, integration data, credentials, and sessions. It cannot be undone.</p><label>Current password<input name="password" type="password" required autoComplete="current-password" /></label><label>Type DELETE MY HEALTHCURVE ACCOUNT<input name="confirmation" required autoComplete="off" /></label><button type="submit" disabled={account.isPending}>Permanently delete account</button>{account.isError ? <p className="error-summary" role="alert">The account was not deleted. Check the password and confirmation phrase.</p> : null}</form></section>
  </Page>;
}
