#!/usr/bin/env python3
"""Detect supported environment variables missing from ``.env.example``.

Only variable names and reviewed classifications are inspected. The private ``.env``
is deliberately never opened, and values from the process environment are never read.
"""

from __future__ import annotations

import re
from pathlib import Path

from healthcurve.config import Settings

_VARIABLE = re.compile(r"\b(?:HC_[A-Z0-9_]+|POSTGRES_(?:PASSWORD|AI_PASSWORD|BACKUP_PASSWORD))\b")
_ASSIGNMENT = re.compile(r"^\s*#?\s*([A-Z][A-Z0-9_]*)\s*=(.*)$")

# These names are intentionally created inside trusted runners or fixed by Compose.
# Keeping the reasons beside the names makes omissions reviewable instead of silently
# excluding an entire prefix from the audit.
INTERNAL_OR_DERIVED = {
    "HC_BACKUP_PROJECT_DIR": "fixed backup-container restore-config path",
    "HC_BACKUP_WORK_ROOT": "fixed backup-container work path",
    "HC_RESTORE_AI_DATABASE_URL": "generated by the isolated restore-drill runner",
    "HC_RESTORE_AI_PASSWORD": "ephemeral restore-drill credential",
    "HC_RESTORE_BACKUP_PASSWORD": "ephemeral restore-drill credential",
    "HC_RESTORE_DATABASE_URL": "generated by the isolated restore-drill runner",
    "HC_RESTORE_DRILL_ENVELOPE": "fixed restore-container input path",
    "HC_RESTORE_DRILL_ENVELOPE_NAME": "derived from the selected backup envelope",
    "HC_RESTORE_DRILL_IDENTITY": "fixed restore-container identity path",
    "HC_RESTORE_DRILL_IDENTITY_FILE": "validated private input to the restore runner",
    "HC_RESTORE_DRILL_INPUT_DIR": "derived from the selected backup envelope",
    "HC_RESTORE_DRILL_WORK_ROOT": "fixed restore-container work path",
    "HC_RESTORE_POSTGRES_PASSWORD": "ephemeral restore-drill credential",
}

# This variable is recognized only so runtime validation can explicitly reject it.
FORBIDDEN = {
    "HC_BACKUP_OFFSITE_MAINTENANCE_CREDENTIAL_FILE": (
        "forbidden in routine runtime; maintenance credentials stay offline"
    ),
}

# A command-example convenience variable, not HealthCurve configuration.
SHELL_LOCAL = {
    "HC_KEY_PATH": "shell-local alias used by the credential-encryption example",
}

OPERATOR_EXTRAS = {
    "POSTGRES_PASSWORD",
    "POSTGRES_AI_PASSWORD",
    "POSTGRES_BACKUP_PASSWORD",
}

# Values that could identify an owner, reveal a credential, or disclose a private
# machine path must remain empty in the public template. Defaults are intentionally
# excluded from this set.
MUST_BE_EMPTY = {
    "POSTGRES_PASSWORD",
    "POSTGRES_AI_PASSWORD",
    "POSTGRES_BACKUP_PASSWORD",
    "HC_ALERT_URL",
    "HC_BACKUP_LOCAL_DIR",
    "HC_BACKUP_OFFSITE_CREDENTIAL_FILE",
    "HC_CREDENTIAL_KEY_FILE",
    "HC_CREDENTIAL_KEY_FILE_HOST",
    "HC_GARMIN_EMAIL",
    "HC_GARMIN_PASSWORD",
    "HC_GARMIN_TOKEN_STORE",
    "HC_GARMIN_TOKEN_STORE_HOST",
    "HC_OWNER_EMAIL",
    "HC_PUBLIC_HEALTHCURVE_ACCOUNT",
    "HC_PUBLIC_HEALTHCURVE_HOST",
    "HC_PUBLIC_HEALTHCURVE_HOST_KEY_SHA256",
    "HC_PUBLIC_HEALTHCURVE_IDENTITY",
    "HC_PUBLIC_HEALTHCURVE_KNOWN_HOSTS",
    "HC_PUBLIC_HEALTHCURVE_RSYNC",
    "HC_RCLONE_CONFIG_FILE_HOST",
    "HC_TELEGRAM_ALLOWED_CHAT_ID",
    "HC_TELEGRAM_BOT_TOKEN",
    "HC_TELEGRAM_WEBHOOK_SECRET",
}


def _source_files(root: Path) -> list[Path]:
    files = [root / "docker-compose.yml"]
    for directory, suffixes in (
        ("src", {".py"}),
        ("scripts", {".py", ".sh"}),
        ("deploy", {".py", ".sh", ".yml", ".yaml"}),
        ("docs", {".md", ".yml", ".yaml"}),
    ):
        files.extend(
            path
            for path in (root / directory).rglob("*")
            if path.is_file() and path.suffix in suffixes
        )
    return sorted(files)


def _references(root: Path) -> set[str]:
    references: set[str] = set()
    for path in _source_files(root):
        references.update(_VARIABLE.findall(path.read_text(encoding="utf-8")))
    # Documentation sometimes says ``HC_CADDY_*``. A trailing underscore is a
    # wildcard prefix, not a usable environment variable.
    return {name for name in references if not name.endswith("_")}


def _documented(path: Path) -> dict[str, str]:
    assignments: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        match = _ASSIGNMENT.match(raw_line)
        if match is None:
            continue
        name, remainder = match.groups()
        # Inline comments in the template start after whitespace. This avoids
        # accidentally truncating a URL fragment while still excluding prose.
        value = remainder.strip()
        if value.startswith("#"):
            value = ""
        else:
            value = re.split(r"\s+#", value, maxsplit=1)[0].strip()
        assignments[name] = value
    return assignments


def audit(root: Path) -> list[str]:
    """Return deterministic, value-free failure descriptions for ``root``."""
    references = _references(root)
    settings = {f"HC_{field.upper()}" for field in Settings.model_fields}
    documented = _documented(root / ".env.example")
    classified = INTERNAL_OR_DERIVED.keys() | FORBIDDEN.keys() | SHELL_LOCAL.keys()

    failures = [
        f"missing_from_env_example:{name}"
        for name in sorted(
            (references | settings | OPERATOR_EXTRAS) - documented.keys() - classified
        )
    ]
    failures.extend(
        f"classified_but_unreferenced:{name}" for name in sorted(classified - references - settings)
    )
    failures.extend(
        f"sensitive_placeholder_must_be_empty:{name}"
        for name in sorted(MUST_BE_EMPTY)
        if documented.get(name, "")
    )
    return failures


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    failures = audit(root)
    for failure in failures:
        print(f"ERROR: {failure}")
    if failures:
        return 1
    print(".env.example covers supported settings; sensitive placeholders are empty")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
