#!/usr/bin/env bash
set -euo pipefail

PUBLIC_SCHEDULE_REPOSITORY="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
PUBLIC_SCHEDULE_FRONTEND="$PUBLIC_SCHEDULE_REPOSITORY/frontend"
PUBLIC_SCHEDULE_STATE="$PUBLIC_SCHEDULE_REPOSITORY/var/public-healthcurve"
PUBLIC_SCHEDULE_LOCK_HASH="$PUBLIC_SCHEDULE_STATE/package-lock.sha256"
mkdir -p "$PUBLIC_SCHEDULE_STATE"

git -C "$PUBLIC_SCHEDULE_REPOSITORY" pull --ff-only origin main

PUBLIC_SCHEDULE_CURRENT_HASH="$(shasum -a 256 "$PUBLIC_SCHEDULE_FRONTEND/package-lock.json" | awk '{print $1}')"
PUBLIC_SCHEDULE_INSTALLED_HASH=""
if [[ -f "$PUBLIC_SCHEDULE_LOCK_HASH" ]]; then
  PUBLIC_SCHEDULE_INSTALLED_HASH="$(<"$PUBLIC_SCHEDULE_LOCK_HASH")"
fi
if [[ ! -d "$PUBLIC_SCHEDULE_FRONTEND/node_modules" || "$PUBLIC_SCHEDULE_INSTALLED_HASH" != "$PUBLIC_SCHEDULE_CURRENT_HASH" ]]; then
  npm --prefix "$PUBLIC_SCHEDULE_FRONTEND" ci
  printf '%s\n' "$PUBLIC_SCHEDULE_CURRENT_HASH" > "$PUBLIC_SCHEDULE_LOCK_HASH"
fi

exec "$PUBLIC_SCHEDULE_REPOSITORY/scripts/publish_public_healthcurve.sh"
